version: "3.8"

services:
  kafka:
    image: bitnamilegacy/kafka:latest
    container_name: kafka-hospital
    ports:
      - "9092:9092"
    environment:
      # Enable KRaft mode
      KAFKA_ENABLE_KRAFT: "yes"

      # Broker & controller roles
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Listeners
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Topic settings
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Allow auto topic creation
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"

    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  kafka_data:
